name: 'Dynamic Matrix From Yaml'
on:
  workflow_dispatch:
    inputs:
      key:
        description: Map Key
        default: example1
        required: true
        type: choice
        options:
          - example1
          - example2
          - example3

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      example_value_array: ${{ steps.set-matrix.outputs.example_value_array }}
    steps:
      - uses: interrobangc/curl-jq-action:main
        id: get-json
        with:
          url: https://raw.githubusercontent.com/interrobangc/curl-jq-action/main/map.json
          jq_query: .${{ github.event.inputs.key }}
      - id: set-matrix
        run: |
          echo "example_value_array=$(echo $matrix)" >> $GITHUB_OUTPUT

  echo:
    needs: setup_matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(needs.setup_matrix.outputs.example_value_array) }}

  run_matrix:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_value: ${{ fromJson(needs.setup_matrix.outputs.example_value_array) }}
    steps:
       - run: echo "Hello ${{ matrix.example_value }}"
