name: 'Dynamic Matrix From Yaml'
on:
  workflow_dispatch:
    inputs:
      key:
        description: Map Key
        default: example1
        required: true
        type: choice
        options:
          - example1
          - example2
          - example3

jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      example_value_array: ${{ steps.set-matrix.outputs.example_value_array }}
    steps:
      - id: set-matrix
        run: |
          curl -s https://raw.githubusercontent.com/interrobangc/curl-jq-action/${GITHUB_REF##*/}/.github/workflows/config/map.json > /tmp/map.json
          matrix=$(jq --arg key "${{ inputs.key }}" '.[$key]' /tmp/map.json)
          echo $matrix
          echo "example_value_array=$(echo $matrix)" >> $GITHUB_OUTPUT

  echo:
    needs: setup_matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(needs.setup_matrix.outputs.example_value_array) }}

  run_matrix:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_value: ${{ fromJson(needs.setup_matrix.outputs.example_value_array) }}
    steps:
       - run: echo "Hello ${{ matrix.example_value }}"
